import { useEffect, useState } from 'react';

export default function ProctoredExam({ apiBaseUrl, userId, onBack }) {
  const [sourceText, setSourceText] = useState('https://youtube.com/watch?v=example');
  const [session, setSession] = useState(null);
  const [status, setStatus] = useState('idle');

  const sourceMaterial = sourceText
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

  const terminateWithReason = async (reason, url = '') => {
    if (!session?._id) return;

    await fetch(`${apiBaseUrl}/api/exam/flag/${session._id}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ reason, url }),
    });

    setStatus(`terminated:${reason}`);
  };

  useEffect(() => {
    if (!session?._id || status.startsWith('terminated')) return undefined;

    const onVisibility = () => {
      if (document.visibilityState !== 'visible') {
        terminateWithReason('Tab switched or browser left');
      }
    };

    const onBlur = () => {
      terminateWithReason('Window blur detected');
    };

    const onMessage = (event) => {
      if (event?.data?.type === 'AI_SITE_DETECTED') {
        terminateWithReason('AI site detected from extension', event.data.url || '');
      }
    };

    document.addEventListener('visibilitychange', onVisibility);
    window.addEventListener('blur', onBlur);
    window.addEventListener('message', onMessage);

    return () => {
      document.removeEventListener('visibilitychange', onVisibility);
      window.removeEventListener('blur', onBlur);
      window.removeEventListener('message', onMessage);
    };
  }, [session, status]);

  const startExam = async () => {
    const response = await fetch(`${apiBaseUrl}/api/exam/start`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId, sourceMaterial }),
    });
    const data = await response.json();
    if (!response.ok) {
      alert(data.error || 'Failed to start exam');
      return;
    }
    setSession(data);
    setStatus('active');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-cyan-200">Proctored Exam</h2>
        <button onClick={onBack} className="rounded-xl border border-slate-600 px-4 py-2">Back</button>
      </div>

      {!session && (
        <div className="rounded-2xl border border-cyan-900/60 bg-slate-900/70 p-5 space-y-4">
          <p className="text-slate-300">Paste related YouTube/PDF links. Questions are generated by Gemini from these sources.</p>
          <textarea value={sourceText} onChange={(e) => setSourceText(e.target.value)} rows={5} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2" />
          <button onClick={startExam} className="rounded-xl bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Start Exam</button>
        </div>
      )}

      {session && (
        <div className="rounded-2xl border border-slate-700 bg-slate-900/70 p-5 space-y-4">
          <p className="text-sm uppercase tracking-wide text-slate-400">Status: {status}</p>
          {status.startsWith('terminated') ? (
            <p className="rounded-xl border border-red-700 bg-red-950/60 px-4 py-3 text-red-200">
              Session terminated due to red flag.
            </p>
          ) : (
            <p className="rounded-xl border border-amber-600 bg-amber-950/40 px-4 py-3 text-amber-200">
              Proctoring is active. Switching tabs or leaving the window ends this exam.
            </p>
          )}

          <div>
            <h3 className="mb-3 text-lg font-semibold">Generated Questions</h3>
            <ol className="list-decimal pl-5 space-y-2 text-slate-200">
              {(session.generatedQuestions || []).map((q) => (
                <li key={q}>{q}</li>
              ))}
            </ol>
          </div>
        </div>
      )}
    </div>
  );
}
